/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:f8788b68-cf1f-4c32-9868-7cf299c03f6d",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_S6UcoM7cS",
    "aws_user_pools_web_client_id": "1c9ssa9lp06jioomvfaf0phn64",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_NUMBERS",
            "REQUIRES_UPPERCASE"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "vatrestapi2",
            "endpoint": "https://177tv4wkq9.execute-api.eu-west-2.amazonaws.com/staging",
            "region": "eu-west-2"
        },
        {
            "name": "hmrcauth",
            "endpoint": "https://pmziml8367.execute-api.eu-west-2.amazonaws.com/staging",
            "region": "eu-west-2"
        },
        {
            "name": "apihmrcvatobligations",
            "endpoint": "https://l5xcyb1vx6.execute-api.eu-west-2.amazonaws.com/staging",
            "region": "eu-west-2"
        },
        {
            "name": "apihmrcgetauthurl",
            "endpoint": "https://cla08ed0xf.execute-api.eu-west-2.amazonaws.com/staging",
            "region": "eu-west-2"
        }
    ],
    "aws_cognito_login_mechanism": []
};


export default awsmobile;
